name: analyze Azure template files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
   runs-on: ubuntu-latest
   permissions:
    contents: read
    security-events: write

   steps:
   - name: Checkout
     uses: actions/checkout@v3
   - run: |
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
        Install-Module -Name Az.Resources -Scope CurrentUser -SkipPublisherCheck -AcceptLicense
     shell: pwsh 
   - name: analyze
     uses: microsoft/ps-rule@v2.3.2
     with:
       inputType: repository
       modules: 'PSRule.Rules.Azure'
       outputFormat: Sarif
       outputPath: reports/ps-rule-results.sarif

   - name: Upload results to security tab
     uses: github/codeql-action/upload-sarif@v2
     with:
      sarif_file: reports/ps-rule-results.sarif
  

