name: analyze Azure template files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout
     uses: actions/checkout@v3
   - run: |
        Install-Module Az.Resources
     shell: pwsh 
   - name: analyze
     uses: microsoft/ps-rule@v2.3.2
     with:
       inputType: repository
       modules: 'PSRule.Rules.Azure'
       outputFormat: Sarif
       outputPath: reports/ps-rule-results.sarif

   - name: Upload results to security tab
     uses: github/codeql-action/upload-sarif@v2
     with:
      sarif_file: reports/ps-rule-results.sarif
  

